Update travis.yml for dev branch

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,6 +31,25 @@ script:
     else
     echo "This branch($TRAVIS_BRANCH) is not available";
     fi
+  - if [ "$TRAVIS_BRANCH" == "dev" ]; then
+    DOCKER_RUN "make index" && INDEX_NON_ERROR=TRUE;
+    if [ "$INDEX_NON_ERROR" != TRUE ]; then echo "Error occured on make index..."; exit 1; fi;
+    DOCKER_RUN "make pages" && PAGES_NON_ERROR=TRUE;
+    if [ "$PAGES_NON_ERROR" == TRUE ]; then
+    for lang in `cat .supportLanguages`; do
+    sudo echo "Starting build $lang...";
+    export PUBLISH_LABEL="Publish-$lang";
+    export PUBLISH_BRANCH="dev-$lang";
+    export PUBLISH_DIR=".publish/$lang";
+    sudo bash .Build.sh/build.sh publish;
+    done;
+    else
+    echo "Error occured on make pages...";
+    exit 1;
+    fi;
+    else
+    echo "This branch($TRAVIS_BRANCH) is not available";
+    fi
   - if [ "$TRAVIS_BRANCH" == "master" ]; then
     DOCKER_RUN "make index" && INDEX_NON_ERROR=TRUE;
     if [ "$INDEX_NON_ERROR" != TRUE ]; then echo "Error occured on make index..."; exit 1; fi;
